global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "go-websockify"
    scrape_interval: 5s
    static_configs:
      - targets: ["go-websockify:8080"]
