{
 "title": "Go WebSockify",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(go_websockify_websocket_bytes_tx_total[10s]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "(sum(rate(go_websockify_websocket_bytes_tx_total[10s])))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Active WebSocket Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(go_websockify_websocket_connections_active)",
     "legendFormat": "Active WebSocket Connections"
    }
   ]
  },
  {
   "title": "Backend TCP Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(go_websockify_tcp_connections_active)",
     "legendFormat": "Backend TCP Connections"
    }
   ]
  }
 ]
}