name: Build Docker

on:
  push:
  pull_request:

runs: 
  using: 'docker'
  image: 'Dockerfile'

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
