name: Build Binary

on:
  push:
  pull_request:

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.5'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo Running action $GITHUB_ACTION
          make
        env:

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: go-websockify
          path: |
            ./bin/go-websockify
