name: Build Binary

on:
  pull_request:

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "BINARY_NAME=go-websockify" >> $GITHUB_ENV

      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.5'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Checkout UPX
        uses: actions/checkout@v2
        with:
          repository: upx/upx
          path: upx

      - name: Build UPX
        run: |
          make all

      - name: Build
        run: |
          echo Running action $GITHUB_ACTION
          make
          upx ./bin/$BINARY_NAME

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: $BINARY_NAME
          path: |
            ./bin/$BINARY_NAME
