name: Build Binary

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.5'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Checkout UPX
        uses: actions/checkout@v2
        with:
          repository: upx/upx
          path: upx
          submodules: true

      - name: Build UPX
        run: |
          cd upx
          make all

      - name: Build Go WebSockify
        run: |
          make

      - name: Compress binary with UPX
        run: |
          upx ./bin/go-websockify

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: go-websockify
          path: |
            ./bin/go-websockify