name: Build Binary

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms: [ 'linux-amd64', 'darwin-amd64' ]
        go: [ '1.15.5' ]

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Go WebSockify
        run: |
          make PLATFORM=${{ matrix.platforms }}

      - name: Compress binary with UPX
        run: |
          upx ./bin/go-websockify-${{ matrix.platforms }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: go-websockify-${{ matrix.platforms }}
          path: |
            ./bin/go-websockify-${{ matrix.platforms }}
